name: Simple Go app
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go Version
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
      - run: go run main.go